// packages/amaui-style-react/src/AmauiStyleProvider/AmauiStyleProvider.tsx
import React from 'react';

import { is } from '@amaui/utils';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject } from '@amaui/style';

import AmauiStyleContext from './AmauiStyleContext';

function makeAmauiStyle(element?: Element) {
  const amauiStyle = new AmauiStyle(element);

  // Add all the plugins
  amauiStyle.plugins.add = [
    makeClassName,
    unit,
    rtl,
    sort,
    valueObject
  ];

  return amauiStyle;
}

export interface IAmauiStyleProvider extends AmauiStyle {
  updateWithRerender?: (value: any) => AmauiStyle;
}

const AmauiStyleProvider = React.forwardRef((props: any, ref: any) => {
  const { children, value: value_, ...other } = props;

  const rootRef = React.useRef<HTMLElement>();

  const [value, setValue] = React.useState(() => {
    if (value_ === undefined || !(value_ instanceof AmauiStyle)) return makeAmauiStyle();

    return value_ as AmauiStyle;
  });

  React.useEffect(() => {
    if (rootRef.current) {
      value.element = rootRef.current;

      // Init
      value.init();

      const valueNew = new AmauiStyle();

      // Copy over from value
      Object.keys(value).forEach(prop => valueNew[prop] = value[prop]);

      setValue(valueNew);
    }
  }, []);

  const update = (updateValue: any) => {
    if (updateValue !== undefined) {
      const valueNew = new AmauiStyle();

      Object.keys(value).forEach(prop => valueNew[prop] = value[prop]);

      is('object', updateValue) && Object.keys(updateValue).forEach(prop => valueNew[prop] = updateValue[prop]);

      setValue(valueNew);

      return valueNew;
    }
  };

  // Update method
  value.updateWithRerender = update;

  return (
    <AmauiStyleContext.Provider value={value}>
      <div
        ref={item => rootRef.current = ref.current = item}

        {...other}
      >
        {children}
      </div>
    </AmauiStyleContext.Provider>
  );
});

export default AmauiStyleProvider;

// packages/amaui-style-web-components/src/AmauiStyleProvider/AmauiStyleProvider.ts
import { isEnvironment } from '@amaui/utils';

import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject } from '@amaui/style';

// Fix for testing ssr
if (isEnvironment('nodejs')) (global as any).HTMLElement = class HTMLElement { }

function makeAmauiStyle(element?: Element) {
  const amauiStyle = new AmauiStyle(element);

  // Add all the plugins
  amauiStyle.plugins.add = [
    makeClassName,
    unit,
    rtl,
    sort,
    valueObject
  ];

  return amauiStyle;
}

export default class AmauiStyleElement extends HTMLElement {
  private value_: AmauiStyle;
  public amaui_style: AmauiStyle;
  public props: any = {};

  public get value() {
    return this.value_;
  }

  public set value(value: AmauiStyle) {
    this.value_ = value;
    this.amaui_style = value;
  }

  public connectedCallback() {
    this.value = this.props.value || makeAmauiStyle(this);

    if (this.props.value) this.value.element = this;

    // Init
    this.value.init();
  }

  public update(updateValue) {
    if (updateValue !== undefined) {
      const valueNew = new AmauiStyle();

      Object.keys(this.value).forEach(prop => valueNew[prop] = this.value[prop]);

      Object.keys(updateValue).forEach(prop => valueNew[prop] = updateValue[prop]);

      this.value = valueNew;

      this.value.element = this;

      this.value.init();

      // Update method
      if ((this.value as any).update === undefined) (this.value as any).update = this.update.bind(this);

      this.rerender();

      return valueNew;
    }
  }

  public rerender() {
    this.replaceChildren(...this.children);
  }
}

// Register in window
if (isEnvironment('browser')) {
  if (!window.customElements.get('amaui-style')) window.customElements.define('amaui-style', AmauiStyleElement);
}
