// packages/amaui-style-vue/src/AmauiStyleProvider/AmauiStyleProvider.tsx
import * as Vue from 'vue';

import { is } from '@amaui/utils';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject, } from '@amaui/style';

function makeAmauiStyle() {
  const amauiStyle = new AmauiStyle();

  // Add all the plugins
  amauiStyle.plugins.add = [makeClassName, unit, rtl, sort, valueObject];

  return amauiStyle;
}

export default {
  props: {
    value: AmauiStyle
  },

  setup(props: any) {
    const { value: value_ } = props;

    const value = Vue.ref<AmauiStyle>(value_ === undefined || !(value_ instanceof AmauiStyle) ? makeAmauiStyle() : value_);

    // Provide
    Vue.provide('amauiStyle', value);

    return {
      value
    };
  },

  mounted() {
    if (this.value.hasOwnProperty('element')) this.value.element = this.$refs.root;

    // Init
    is('function', this.value.init) && this.value.init();
  },

  render() {
    const { value, ...other } = this.$props;

    return (
      <div ref='root' {...other}>
        {this.$slots.default && this.$slots.default()}
      </div>
    );
  }
};

// packages/amaui-style-react/src/AmauiStyleProvider/AmauiStyleProvider.tsx
import React from 'react';

import is from '@amaui/utils/is';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject } from '@amaui/style';

import AmauiStyleContext from './AmauiStyleContext';

function makeAmauiStyle(element?: Element) {
  const amauiStyle = new AmauiStyle({
    element
  });

  // Add all the plugins
  amauiStyle.plugins.add = [
    unit,
    makeClassName,
    rtl,
    sort,
    valueObject
  ];

  return amauiStyle;
}

export interface IAmauiStyleProvider extends AmauiStyle {
  updateWithRerender?: (value: any) => AmauiStyle;
}

const AmauiStyleProvider = React.forwardRef((props: any, ref: any) => {
  const {
    root = false,

    value: value_,

    children,

    ...other
  } = props;

  const refs = {
    root: React.useRef<any>()
  };

  const [value, setValue] = React.useState(() => {
    if (value_ === undefined || !(value_ instanceof AmauiStyle)) return makeAmauiStyle();

    return value_ as AmauiStyle;
  });

  React.useEffect(() => {
    if (refs.root.current) {
      value.element = refs.root.current;

      // Init
      value.init();

      const valueNew = new AmauiStyle();

      // Copy over from value
      Object.keys(value).forEach((prop: any) => valueNew[prop] = value[prop]);

      setValue(valueNew);
    }
  }, []);

  const update = (updateValue: any) => {
    if (updateValue !== undefined) {
      const valueNew = new AmauiStyle();

      Object.keys(value).forEach((prop: any) => valueNew[prop] = value[prop]);

      is('object', updateValue) && Object.keys(updateValue).forEach((prop: any) => valueNew[prop] = updateValue[prop]);

      setValue(valueNew);

      return valueNew;
    }
  };

  // Update method
  value.updateWithRerender = update;

  if (root) return (
    <AmauiStyleContext.Provider
      value={value}
    >
      <div
        ref={(item: any) => {
          refs.root.current = item;

          if (ref?.current) ref.current = item;
        }}

        {...other}
      >
        {children}
      </div>
    </AmauiStyleContext.Provider>
  );

  return (
    <AmauiStyleContext.Provider
      value={value}
    >
      {children}
    </AmauiStyleContext.Provider>
  );
});

export default AmauiStyleProvider;
