// packages/amaui-style-react/src/AmauiThemeProvider/AmauiThemeProvider.tsx
import React from 'react';

import { hash, merge } from '@amaui/utils';
import { AmauiTheme } from '@amaui/style';

import AmauiThemeContext from './AmauiThemeContext';
import useAmauiTheme from './useAmauiTheme';

export default function AmauiThemeProvider(props) {
  const { children, value: valueLocal, ...other } = props;

  const ref = React.useRef();

  const valueParentTheme = (useAmauiTheme() || [])[0];

  const valueParent = React.useMemo(() => {
    return valueParentTheme || {};
  }, [(valueParentTheme as AmauiTheme)?.hash]);

  const [value] = React.useState(new AmauiTheme(merge({ ...valueLocal }, { ...valueParent }, { copy: true })));
  const setId = React.useState(undefined)[1];

  React.useEffect(() => {
    if (ref.current) {
      value.element = ref.current;

      // Init
      value.init();

      setId(hash(value));
    }
  }, []);

  React.useEffect(() => {
    // Update
    value.update(merge({ ...valueLocal }, { ...valueParent }, { copy: true }));

    setId(hash(value));
  }, [hash(valueLocal), hash(valueParent)]);

  const update = (updateValue: any) => {
    if (updateValue !== undefined) {
      // Update
      value.update(updateValue);

      setId(hash(value));

      return value;
    }
  };

  return (
    <AmauiThemeContext.Provider value={[value, update]}>
      <div ref={ref} {...other}>
        {children}
      </div>
    </AmauiThemeContext.Provider>
  );
}

// packages/amaui-style-vue/src/AmauiThemeProvider/AmauiThemeProvider.tsx
import * as Vue from 'vue';

import { copy, merge } from '@amaui/utils';
import { AmauiTheme } from '@amaui/style';

export default {
  props: {
    value: [Object, AmauiTheme],
  },

  setup(props: any) {
    const { value: valueLocal } = Vue.toRefs(props);

    const valueParent = Vue.inject<AmauiTheme>('amauiTheme');

    const value = Vue.ref(new AmauiTheme(merge(copy({ ...valueLocal.value }), copy({ ...(valueParent?.value || {}) }), { copy: true })));

    // Value local
    if (valueLocal.value) Vue.watch(valueLocal.value, valueNew => {
      value.value.update(merge(copy({ ...valueNew }), copy({ ...(valueParent?.value || {}) }), { copy: true }));
    });

    // Value parent
    if (valueParent) Vue.watch(valueParent.value, valueNew => {
      value.value.update(merge(copy({ ...valueLocal.value }), copy({ ...(valueNew || {}) }), { copy: true }));
    });

    Vue.provide('amauiTheme', value);

    return {
      value
    };
  },

  mounted() {
    this.value.element = this.$refs.root;

    // Init
    this.value.init && this.value.init();
  },

  render() {
    const { value, ...other } = this.$props;

    return (
      <div ref='root' {...other}>
        {this.$slots.default && this.$slots.default()}
      </div>
    );
  }
};
