// packages/amaui-style-vue/src/withStyle.tsx
// import Vue from 'vue';

// import { TValue } from '@amaui/style';
// import { IOptions } from '@amaui/style/style';

// import { style } from '.';

// const withStyle = (Element: Vue.VueElement) => (value: TValue, options: IOptions = {}) => {
//   // Use styles
//   const useStyle = style(value, options);

//   return {
//     extends: Element,
//     created() {
//       const values = useStyle(this.$props);

//       this.style = values;
//     },
//   };
// };

// export default withStyle;

// packages/amaui-style-react/src/withStyle.tsx
import React from 'react';

import { TValue } from '@amaui/style';
import { IOptions } from '@amaui/style/style';

import { style } from '.';

const withStyle = (Element: any) => (value: TValue, options: IOptions = {}): React.ElementType => {
  // Use styles
  const useStyle = style(value, options);

  // Element
  const element = React.forwardRef((props: any, ref) => {
    const styles = useStyle(props);

    return (
      <Element ref={ref} styles={styles} {...props} />
    );
  });

  return element;
};

export default withStyle;
