// packages/amaui-style-react/src/AmauiThemeProvider/AmauiThemeProvider.tsx
import React from 'react';

import { hash, merge } from '@amaui/utils';
import { AmauiTheme } from '@amaui/style';

import AmauiThemeContext from './AmauiThemeContext';
import useAmauiTheme from './useAmauiTheme';

export default function AmauiThemeProvider(props) {
  const { children, value: valueLocal, ...other } = props;

  const ref = React.useRef();

  const valueParentTheme = (useAmauiTheme() || [])[0];

  const valueParent = React.useMemo(() => {
    return valueParentTheme || {};
  }, [(valueParentTheme as AmauiTheme)?.hash]);

  const [value] = React.useState(new AmauiTheme(merge({ ...valueLocal }, { ...valueParent }, { copy: true })));
  const setId = React.useState(undefined)[1];

  React.useEffect(() => {
    if (ref.current) {
      value.element = ref.current;

      // Init
      value.init();

      setId(hash(value));
    }
  }, []);

  React.useEffect(() => {
    // Update
    value.update(merge({ ...valueLocal }, { ...valueParent }, { copy: true }));

    setId(hash(value));
  }, [hash(valueLocal), hash(valueParent)]);

  const update = (updateValue: any) => {
    if (updateValue !== undefined) {
      // Update
      value.update(updateValue);

      setId(hash(value));

      return value;
    }
  };

  return (
    <AmauiThemeContext.Provider value={[value, update]}>
      <div ref={ref} {...other}>
        {children}
      </div>
    </AmauiThemeContext.Provider>
  );
}

// packages/amaui-style-vue/src/AmauiThemeProvider.tsx
import * as Vue from 'vue';

import { merge } from '@amaui/utils';
import { AmauiTheme } from '@amaui/style';

export default {
  props: {
    value: AmauiTheme,
  },

  setup(props: any) {
    const { value: valueLocal = {} } = props;

    const valueParent = Vue.inject<AmauiTheme>('amauiTheme').value || {};

    const value = Vue.ref(new AmauiTheme(merge({ ...valueLocal }, { ...valueParent }, { copy: true })));

    // Value local
    Vue.watch(valueLocal, valueNew => {
      value.value.update(merge({ ...valueNew }, { ...valueParent }, { copy: true }));
    });

    // Value parent
    Vue.watch(valueParent, valueNew => {
      value.value.update(merge({ ...valueLocal }, { ...valueNew }, { copy: true }));
    });

    Vue.provide('amauiTheme', value);

    return {
      value
    };
  },

  mounted() {
    if (this.value.hasOwnProperty('element')) this.value.element = this.$refs.root;

    // Init
    this.value.init && this.value.init();
  },

  render() {
    const slots = Vue.useSlots();

    return (
      Vue.h(
        'div',
        {
          ref: 'root'
        },
        slots.default && slots.default()
      )
    );
  }
};
