// packages/amaui-style-react/src/AmauiStyleProvider/AmauiStyleProvider.tsx
import React from 'react';

import { merge } from '@amaui/utils';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject } from '@amaui/style';

import AmauiStyleContext from './AmauiStyleContext';

function makeAmauiStyle() {
  const amauiStyle = new AmauiStyle();

  // Add all the plugins
  amauiStyle.plugins.add = [
    makeClassName,
    unit,
    rtl,
    sort,
    valueObject
  ];

  return amauiStyle;
}

export default function AmauiStyleProvider(props) {
  const { children, value: value_ } = props;

  const [value, setValue] = React.useState(() => {
    if (value_ === undefined || !(value_ instanceof AmauiStyle)) return makeAmauiStyle();

    return value_;
  });

  const update = (updateValue: any, override = false) => {
    if (updateValue !== undefined) {
      const valueNew = override ? updateValue : merge(updateValue, value);

      setValue(valueNew);

      return valueNew;
    }
  };

  return (
    <AmauiStyleContext.Provider
      value={[value, update]}
    >
      {children}
    </AmauiStyleContext.Provider>
  );
}

// packages/amaui-style-vue/src/AmauiStyleProvider.tsx
import Vue from 'vue';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject, } from '@amaui/style';

function makeAmauiStyle() {
  const amauiStyle = new AmauiStyle();

  // Add all the plugins
  amauiStyle.plugins.add = [makeClassName, unit, rtl, sort, valueObject];

  return amauiStyle;
}

export default {
  props: {
    value: AmauiStyle,
  },
  setup(props: any) {
    const { value } = Vue.toRefs(props);

    let value_: AmauiStyle;

    if (value === undefined || !(value instanceof AmauiStyle)) value_ = makeAmauiStyle();

    Vue.provide("amauiStyle", value_);

    return {};
  },
  render() {
    return (
      <template>
        {this.$slots.default}
      </template>
    );
  }
};
