// packages/amaui-style-react/src/styled.tsx
import React from 'react';

import { classNames, TValue } from '@amaui/style';
import { IOptions } from '@amaui/style/style';

import { style } from '.';

const styled = (Element: any) => (value: TValue, options: IOptions = {}): React.ElementType => {
  // Use styles
  const useStyle = style(value, options);

  // Element
  const element = React.forwardRef((props: any, ref) => {
    const {
      children,
      className: classNameProp,
      ...other
    } = props;

    const styles = useStyle(props);

    return (
      <Element
        ref={ref}

        className={classNames([classNameProp, styles.class])}

        {...other}
      >
        {children}
      </Element>
    );
  });

  return element;
};

export default styled;

// packages/amaui-style-vue/src/styled.tsx
import * as Vue from 'vue';

import { classNames, TValue } from '@amaui/style';
import { IOptions } from '@amaui/style/style';

import { style } from '.';

const styled = (Element: any) => (value: TValue, options: IOptions = {}) => {
  // Use styles
  const useStyle = style(value, options);

  // Element
  const element = Vue.defineComponent({
    props: ['ref', 'class'],

    setup(props: any, { slots, attrs }) {
      const attrs_ = Vue.ref(attrs);

      const { ref, class: classProp } = props;

      const styles = useStyle(attrs_);

      return () => (
        <Element
          ref={ref}

          class={classNames([classProp, styles.value.class])}
        >
          {slots.default && slots.default()}
        </Element>
      );
    }
  });

  return element;
};

export default styled;
