// packages/amaui-style-web-components/src/AmauiStyleProvider.ts
import { isEnvironment } from '@amaui/utils';

import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject } from '@amaui/style';

function makeAmauiStyle(element: Element) {
  const amauiStyle = new AmauiStyle(element);

  // Add all the plugins
  amauiStyle.plugins.add = [
    makeClassName,
    unit,
    rtl,
    sort,
    valueObject
  ];

  return amauiStyle;
}

export default class AmauiStyleElement extends HTMLElement {

  public constructor() {
    super();

    this.attachShadow({ mode: 'open' });

    this.shadowRoot.innerHTML = `<slot />`;
  }

  public connectedCallback() {
    if (!this.isConnected) {
      let value: AmauiStyle = (this as any).value;

      if (value === undefined || !(value instanceof AmauiStyle)) value = makeAmauiStyle(this);

      // Add value to the instance
      (this as any).value = value;
    }
  }

}

// Register in window
if (isEnvironment('browser')) {
  if (!window.customElements.get('amaui-style')) window.customElements.define('amaui-style', AmauiStyleElement);
}

// packages/amaui-style-vue/src/AmauiStyleProvider/AmauiStyleProvider.tsx
import * as Vue from 'vue';

import { is } from '@amaui/utils';
import { AmauiStyle, makeClassName, unit, rtl, sort, valueObject, } from '@amaui/style';

function makeAmauiStyle() {
  const amauiStyle = new AmauiStyle();

  // Add all the plugins
  amauiStyle.plugins.add = [makeClassName, unit, rtl, sort, valueObject];

  return amauiStyle;
}

export default {
  props: {
    value: AmauiStyle
  },

  setup(props: any) {
    const { value: value_ } = props;

    const value = Vue.ref<AmauiStyle>(value_ === undefined || !(value_ instanceof AmauiStyle) ? makeAmauiStyle() : value_);

    // Provide
    Vue.provide('amauiStyle', value);

    return {
      value
    };
  },

  mounted() {
    if (this.value.hasOwnProperty('element')) this.value.element = this.$refs.root;

    // Init
    is('function', this.value.init) && this.value.init();
  },

  render() {
    const { value, ...other } = this.$props;

    return (
      <div ref='root' {...other}>
        {this.$slots.default && this.$slots.default()}
      </div>
    );
  }
};
